name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Package mod
      run: zip -r personal_logistic_plates_${{ github.ref_name }}.zip . -x "*.git*" -x ".github/**" -x ".vscode"

    - name: GH Release
      uses: softprops/action-gh-release@v2
      with:
        files: personal_logistic_plates_${{ github.ref_name }}.zip